# Generated by Django 4.2.4 on 2023-08-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0001_initial"),
        ("garagem", "0003_remove_veiculo_imagem_veiculo_imagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="veiculo",
            name="acessorio",
            field=models.ManyToManyField(to="garagem.acessorio"),
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="descricao",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="imagem",
            field=models.ManyToManyField(blank=True, default=None, related_name="+", to="uploader.image"),
        ),
    ]
